//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XIT.tTestLog {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="tTestLog.tTestLogSoap")]
    public interface tTestLogSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveTestLogWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveTestLogWeb(XIT.tTestLog.TtestInfo[] sti);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryAteLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QueryAteLog(string Esn, string WorkOrder, string TestStation);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TtestInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string esnField;
        
        private string workOrderField;
        
        private string testStationField;
        
        private string itemNameField;
        
        private int testResultField;
        
        private double testDataField;
        
        private int testCountField;
        
        private System.DateTime testTimeField;
        
        private string pcNameField;
        
        private string noteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Esn {
            get {
                return this.esnField;
            }
            set {
                this.esnField = value;
                this.RaisePropertyChanged("Esn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string WorkOrder {
            get {
                return this.workOrderField;
            }
            set {
                this.workOrderField = value;
                this.RaisePropertyChanged("WorkOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TestStation {
            get {
                return this.testStationField;
            }
            set {
                this.testStationField = value;
                this.RaisePropertyChanged("TestStation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
                this.RaisePropertyChanged("ItemName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int TestResult {
            get {
                return this.testResultField;
            }
            set {
                this.testResultField = value;
                this.RaisePropertyChanged("TestResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double TestData {
            get {
                return this.testDataField;
            }
            set {
                this.testDataField = value;
                this.RaisePropertyChanged("TestData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int TestCount {
            get {
                return this.testCountField;
            }
            set {
                this.testCountField = value;
                this.RaisePropertyChanged("TestCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime TestTime {
            get {
                return this.testTimeField;
            }
            set {
                this.testTimeField = value;
                this.RaisePropertyChanged("TestTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PcName {
            get {
                return this.pcNameField;
            }
            set {
                this.pcNameField = value;
                this.RaisePropertyChanged("PcName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface tTestLogSoapChannel : XIT.tTestLog.tTestLogSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class tTestLogSoapClient : System.ServiceModel.ClientBase<XIT.tTestLog.tTestLogSoap>, XIT.tTestLog.tTestLogSoap {
        
        public tTestLogSoapClient() {
        }
        
        public tTestLogSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public tTestLogSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tTestLogSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tTestLogSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public string SaveTestLogWeb(XIT.tTestLog.TtestInfo[] sti) {
            return base.Channel.SaveTestLogWeb(sti);
        }
        
        public System.Data.DataSet QueryAteLog(string Esn, string WorkOrder, string TestStation) {
            return base.Channel.QueryAteLog(Esn, WorkOrder, TestStation);
        }
    }
}
