//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XIT.tCheckDataTestAte {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="tCheckDataTestAte.tCheckDataTestAteSoap")]
    public interface tCheckDataTestAteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckEmp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckEmp(string EMP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckEmp_NEW", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckEmp_NEW(string EMP, string ipaddress, string macaddress, string mygroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllStation(string woId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStationXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAllStationXML(string woId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWOCraftInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetWOCraftInfo(string woId, string Flag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCraftInfoByRouteId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetCraftInfoByRouteId(string RouteId, string Flag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Check_Route_ATE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Check_Route_ATE(string DATA, string Route, string WO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INS_ATE_Back", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string INS_ATE_Back(string DATA, string Route, string EMP, string LINE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INS_ATE_BACK_INS_WIPKEYPARTS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string INS_ATE_BACK_INS_WIPKEYPARTS(string DATA, string MYGROUP, string EMP, string LINE, XIT.tCheckDataTestAte.tWipKeyPartTable[] lswipkeypart, int Flag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLineList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLineList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLineListXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetLineListXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWOSnRule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetWOSnRule(string woId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWOSnRuleXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetWOSnRuleXML(string woId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertWipKeyParts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertWipKeyParts(XIT.tCheckDataTestAte.tWipKeyPartTable[] lswipkeypart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEsnDataInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetEsnDataInfo(string sntype, string snval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEsnDataInfoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetEsnDataInfoXML(string sntype, string snval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEsnDataInfoXMLBySntype", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetEsnDataInfoXMLBySntype(string sntype, string snval, string[] arrSntype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEsnDataInfoBySntype", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetEsnDataInfoBySntype(string sntype, string snval, string[] arrSntype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSnInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSnInfo(string serial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSnInfoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSnInfoXML(string serial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWipAndRecCartonBox", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateWipAndRecCartonBox(XIT.tCheckDataTestAte.tWipTrackingTable wiptrack);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSnWipKeyPartsData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSnWipKeyPartsData(string SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSnWipKeyPartsDataXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSnWipKeyPartsDataXML(string SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWoList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetWoList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetATEScripts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetATEScripts(string woid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAteScriptsStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAteScriptsStr(string woId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAteScriptsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAteScriptsXML(string woId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteLogOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteLogOut(string userId, string strIpaddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCartonPrintContent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCartonPrintContent(string cartonId, string[] Content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SP_TEST_INPUT_ALL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SP_TEST_INPUT_ALL(XIT.tCheckDataTestAte.tPublicParamForSP Tpfs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChkUserAteEmp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChkUserAteEmp(XIT.tCheckDataTestAte.tAteEmp ateemp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetErrorCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetErrorCode(string ec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetErrorCodeXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetErrorCodeXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SP_PRO_SN_INPUT_MOBILE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SP_PRO_SN_INPUT_MOBILE(string DATA, string MYGROUP, string LINE, string WO, string EMP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWoInfoByWo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetWoInfoByWo(string woId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWoInfoByWoXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetWoInfoByWoXml(string woId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductByPartNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetProductByPartNumber(string PartNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductLableNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetProductLableNames(string partnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSnMacImeiForAte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetSnMacImeiForAte(string Esn, string sntype, string woId, int snqty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSnMacImeiForAte_2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetSnMacImeiForAte_2(out string _StrErr, string Esn, string sntype, string woId, int snqty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_T_TESTRESULT_INFO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insert_T_TESTRESULT_INFO(XIT.tCheckDataTestAte.tT_TESTRESULT_INFO tti);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWoVersionInfoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetWoVersionInfoXML(string woid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPnMarkBitInfoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPnMarkBitInfoXML(string pn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWoVersionInfoDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetWoVersionInfoDataSet(string woid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPnMarkBitInfoDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPnMarkBitInfoDataSet(string pn);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tWipKeyPartTable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idxField;
        
        private string esnField;
        
        private string woIdField;
        
        private string sntypeField;
        
        private string snvalField;
        
        private string stationField;
        
        private string kPNOField;
        
        private string recdateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idx {
            get {
                return this.idxField;
            }
            set {
                this.idxField = value;
                this.RaisePropertyChanged("idx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string esn {
            get {
                return this.esnField;
            }
            set {
                this.esnField = value;
                this.RaisePropertyChanged("esn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string woId {
            get {
                return this.woIdField;
            }
            set {
                this.woIdField = value;
                this.RaisePropertyChanged("woId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sntype {
            get {
                return this.sntypeField;
            }
            set {
                this.sntypeField = value;
                this.RaisePropertyChanged("sntype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string snval {
            get {
                return this.snvalField;
            }
            set {
                this.snvalField = value;
                this.RaisePropertyChanged("snval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string station {
            get {
                return this.stationField;
            }
            set {
                this.stationField = value;
                this.RaisePropertyChanged("station");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string KPNO {
            get {
                return this.kPNOField;
            }
            set {
                this.kPNOField = value;
                this.RaisePropertyChanged("KPNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string recdate {
            get {
                return this.recdateField;
            }
            set {
                this.recdateField = value;
                this.RaisePropertyChanged("recdate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tT_TESTRESULT_INFO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eSNField;
        
        private string wOIDField;
        
        private string tESTSTATIONField;
        
        private string tESTRESULTField;
        
        private string eQPIDField;
        
        private string eQPTYPEField;
        
        private string cUSERField;
        
        private string fAILDESCField;
        
        private string pARTNUMBERField;
        
        private string pRODUCTNAMEField;
        
        private string repairFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ESN {
            get {
                return this.eSNField;
            }
            set {
                this.eSNField = value;
                this.RaisePropertyChanged("ESN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string WOID {
            get {
                return this.wOIDField;
            }
            set {
                this.wOIDField = value;
                this.RaisePropertyChanged("WOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TESTSTATION {
            get {
                return this.tESTSTATIONField;
            }
            set {
                this.tESTSTATIONField = value;
                this.RaisePropertyChanged("TESTSTATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TESTRESULT {
            get {
                return this.tESTRESULTField;
            }
            set {
                this.tESTRESULTField = value;
                this.RaisePropertyChanged("TESTRESULT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EQPID {
            get {
                return this.eQPIDField;
            }
            set {
                this.eQPIDField = value;
                this.RaisePropertyChanged("EQPID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string EQPTYPE {
            get {
                return this.eQPTYPEField;
            }
            set {
                this.eQPTYPEField = value;
                this.RaisePropertyChanged("EQPTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CUSER {
            get {
                return this.cUSERField;
            }
            set {
                this.cUSERField = value;
                this.RaisePropertyChanged("CUSER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FAILDESC {
            get {
                return this.fAILDESCField;
            }
            set {
                this.fAILDESCField = value;
                this.RaisePropertyChanged("FAILDESC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PARTNUMBER {
            get {
                return this.pARTNUMBERField;
            }
            set {
                this.pARTNUMBERField = value;
                this.RaisePropertyChanged("PARTNUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PRODUCTNAME {
            get {
                return this.pRODUCTNAMEField;
            }
            set {
                this.pRODUCTNAMEField = value;
                this.RaisePropertyChanged("PRODUCTNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string RepairFlag {
            get {
                return this.repairFlagField;
            }
            set {
                this.repairFlagField = value;
                this.RaisePropertyChanged("RepairFlag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tAteEmp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string craftIdField;
        
        private string craftnameField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string craftId {
            get {
                return this.craftIdField;
            }
            set {
                this.craftIdField = value;
                this.RaisePropertyChanged("craftId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string craftname {
            get {
                return this.craftnameField;
            }
            set {
                this.craftnameField = value;
                this.RaisePropertyChanged("craftname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tPublicParamForSP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dATAField;
        
        private string mYGROUPField;
        
        private string rOUTECODEField;
        
        private string eRRORFLAGField;
        
        private string lOCSTATIONField;
        
        private string nEXTSTATIONField;
        
        private string woIdField;
        
        private string eNDGROUPField;
        
        private string lINEField;
        
        private string eMPNOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DATA {
            get {
                return this.dATAField;
            }
            set {
                this.dATAField = value;
                this.RaisePropertyChanged("DATA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MYGROUP {
            get {
                return this.mYGROUPField;
            }
            set {
                this.mYGROUPField = value;
                this.RaisePropertyChanged("MYGROUP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ROUTECODE {
            get {
                return this.rOUTECODEField;
            }
            set {
                this.rOUTECODEField = value;
                this.RaisePropertyChanged("ROUTECODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ERRORFLAG {
            get {
                return this.eRRORFLAGField;
            }
            set {
                this.eRRORFLAGField = value;
                this.RaisePropertyChanged("ERRORFLAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LOCSTATION {
            get {
                return this.lOCSTATIONField;
            }
            set {
                this.lOCSTATIONField = value;
                this.RaisePropertyChanged("LOCSTATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NEXTSTATION {
            get {
                return this.nEXTSTATIONField;
            }
            set {
                this.nEXTSTATIONField = value;
                this.RaisePropertyChanged("NEXTSTATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string woId {
            get {
                return this.woIdField;
            }
            set {
                this.woIdField = value;
                this.RaisePropertyChanged("woId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ENDGROUP {
            get {
                return this.eNDGROUPField;
            }
            set {
                this.eNDGROUPField = value;
                this.RaisePropertyChanged("ENDGROUP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string LINE {
            get {
                return this.lINEField;
            }
            set {
                this.lINEField = value;
                this.RaisePropertyChanged("LINE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EMPNO {
            get {
                return this.eMPNOField;
            }
            set {
                this.eMPNOField = value;
                this.RaisePropertyChanged("EMPNO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tWipTrackingTable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eSNField;
        
        private string woField;
        
        private string partNumberField;
        
        private string locstationField;
        
        private string wipstationField;
        
        private string nextstationField;
        
        private string userIdField;
        
        private string recdateField;
        
        private string errflagField;
        
        private string scrapflagField;
        
        private string cartonnumberField;
        
        private string trayNOField;
        
        private string palletnumberField;
        
        private string snField;
        
        private string mACField;
        
        private string mcartonnumbrField;
        
        private string mpalletnumberField;
        
        private string lineField;
        
        private string routgroupIdField;
        
        private string storenumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ESN {
            get {
                return this.eSNField;
            }
            set {
                this.eSNField = value;
                this.RaisePropertyChanged("ESN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string WO {
            get {
                return this.woField;
            }
            set {
                this.woField = value;
                this.RaisePropertyChanged("WO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PartNumber {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
                this.RaisePropertyChanged("PartNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string locstation {
            get {
                return this.locstationField;
            }
            set {
                this.locstationField = value;
                this.RaisePropertyChanged("locstation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string wipstation {
            get {
                return this.wipstationField;
            }
            set {
                this.wipstationField = value;
                this.RaisePropertyChanged("wipstation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string nextstation {
            get {
                return this.nextstationField;
            }
            set {
                this.nextstationField = value;
                this.RaisePropertyChanged("nextstation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string recdate {
            get {
                return this.recdateField;
            }
            set {
                this.recdateField = value;
                this.RaisePropertyChanged("recdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string errflag {
            get {
                return this.errflagField;
            }
            set {
                this.errflagField = value;
                this.RaisePropertyChanged("errflag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string scrapflag {
            get {
                return this.scrapflagField;
            }
            set {
                this.scrapflagField = value;
                this.RaisePropertyChanged("scrapflag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string cartonnumber {
            get {
                return this.cartonnumberField;
            }
            set {
                this.cartonnumberField = value;
                this.RaisePropertyChanged("cartonnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string TrayNO {
            get {
                return this.trayNOField;
            }
            set {
                this.trayNOField = value;
                this.RaisePropertyChanged("TrayNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string palletnumber {
            get {
                return this.palletnumberField;
            }
            set {
                this.palletnumberField = value;
                this.RaisePropertyChanged("palletnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string SN {
            get {
                return this.snField;
            }
            set {
                this.snField = value;
                this.RaisePropertyChanged("SN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string MAC {
            get {
                return this.mACField;
            }
            set {
                this.mACField = value;
                this.RaisePropertyChanged("MAC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string mcartonnumbr {
            get {
                return this.mcartonnumbrField;
            }
            set {
                this.mcartonnumbrField = value;
                this.RaisePropertyChanged("mcartonnumbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string mpalletnumber {
            get {
                return this.mpalletnumberField;
            }
            set {
                this.mpalletnumberField = value;
                this.RaisePropertyChanged("mpalletnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
                this.RaisePropertyChanged("line");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string routgroupId {
            get {
                return this.routgroupIdField;
            }
            set {
                this.routgroupIdField = value;
                this.RaisePropertyChanged("routgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string storenumber {
            get {
                return this.storenumberField;
            }
            set {
                this.storenumberField = value;
                this.RaisePropertyChanged("storenumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface tCheckDataTestAteSoapChannel : XIT.tCheckDataTestAte.tCheckDataTestAteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class tCheckDataTestAteSoapClient : System.ServiceModel.ClientBase<XIT.tCheckDataTestAte.tCheckDataTestAteSoap>, XIT.tCheckDataTestAte.tCheckDataTestAteSoap {
        
        public tCheckDataTestAteSoapClient() {
        }
        
        public tCheckDataTestAteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public tCheckDataTestAteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tCheckDataTestAteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tCheckDataTestAteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckEmp(string EMP) {
            return base.Channel.CheckEmp(EMP);
        }
        
        public string CheckEmp_NEW(string EMP, string ipaddress, string macaddress, string mygroup) {
            return base.Channel.CheckEmp_NEW(EMP, ipaddress, macaddress, mygroup);
        }
        
        public System.Data.DataSet GetAllStation(string woId) {
            return base.Channel.GetAllStation(woId);
        }
        
        public string GetAllStationXML(string woId) {
            return base.Channel.GetAllStationXML(woId);
        }
        
        public string[] GetWOCraftInfo(string woId, string Flag) {
            return base.Channel.GetWOCraftInfo(woId, Flag);
        }
        
        public string[] GetCraftInfoByRouteId(string RouteId, string Flag) {
            return base.Channel.GetCraftInfoByRouteId(RouteId, Flag);
        }
        
        public string Check_Route_ATE(string DATA, string Route, string WO) {
            return base.Channel.Check_Route_ATE(DATA, Route, WO);
        }
        
        public string INS_ATE_Back(string DATA, string Route, string EMP, string LINE) {
            return base.Channel.INS_ATE_Back(DATA, Route, EMP, LINE);
        }
        
        public string INS_ATE_BACK_INS_WIPKEYPARTS(string DATA, string MYGROUP, string EMP, string LINE, XIT.tCheckDataTestAte.tWipKeyPartTable[] lswipkeypart, int Flag) {
            return base.Channel.INS_ATE_BACK_INS_WIPKEYPARTS(DATA, MYGROUP, EMP, LINE, lswipkeypart, Flag);
        }
        
        public System.Data.DataSet GetLineList() {
            return base.Channel.GetLineList();
        }
        
        public string GetLineListXML() {
            return base.Channel.GetLineListXML();
        }
        
        public System.Data.DataSet GetWOSnRule(string woId) {
            return base.Channel.GetWOSnRule(woId);
        }
        
        public string GetWOSnRuleXML(string woId) {
            return base.Channel.GetWOSnRuleXML(woId);
        }
        
        public string InsertWipKeyParts(XIT.tCheckDataTestAte.tWipKeyPartTable[] lswipkeypart) {
            return base.Channel.InsertWipKeyParts(lswipkeypart);
        }
        
        public System.Data.DataSet GetEsnDataInfo(string sntype, string snval) {
            return base.Channel.GetEsnDataInfo(sntype, snval);
        }
        
        public string GetEsnDataInfoXML(string sntype, string snval) {
            return base.Channel.GetEsnDataInfoXML(sntype, snval);
        }
        
        public string GetEsnDataInfoXMLBySntype(string sntype, string snval, string[] arrSntype) {
            return base.Channel.GetEsnDataInfoXMLBySntype(sntype, snval, arrSntype);
        }
        
        public System.Data.DataSet GetEsnDataInfoBySntype(string sntype, string snval, string[] arrSntype) {
            return base.Channel.GetEsnDataInfoBySntype(sntype, snval, arrSntype);
        }
        
        public System.Data.DataSet GetSnInfo(string serial) {
            return base.Channel.GetSnInfo(serial);
        }
        
        public string GetSnInfoXML(string serial) {
            return base.Channel.GetSnInfoXML(serial);
        }
        
        public string UpdateWipAndRecCartonBox(XIT.tCheckDataTestAte.tWipTrackingTable wiptrack) {
            return base.Channel.UpdateWipAndRecCartonBox(wiptrack);
        }
        
        public System.Data.DataSet GetSnWipKeyPartsData(string SN) {
            return base.Channel.GetSnWipKeyPartsData(SN);
        }
        
        public string GetSnWipKeyPartsDataXML(string SN) {
            return base.Channel.GetSnWipKeyPartsDataXML(SN);
        }
        
        public string[] GetWoList() {
            return base.Channel.GetWoList();
        }
        
        public System.Data.DataSet GetATEScripts(string woid) {
            return base.Channel.GetATEScripts(woid);
        }
        
        public string GetAteScriptsStr(string woId) {
            return base.Channel.GetAteScriptsStr(woId);
        }
        
        public string GetAteScriptsXML(string woId) {
            return base.Channel.GetAteScriptsXML(woId);
        }
        
        public string DeleteLogOut(string userId, string strIpaddress) {
            return base.Channel.DeleteLogOut(userId, strIpaddress);
        }
        
        public System.Data.DataSet GetCartonPrintContent(string cartonId, string[] Content) {
            return base.Channel.GetCartonPrintContent(cartonId, Content);
        }
        
        public string SP_TEST_INPUT_ALL(XIT.tCheckDataTestAte.tPublicParamForSP Tpfs) {
            return base.Channel.SP_TEST_INPUT_ALL(Tpfs);
        }
        
        public string ChkUserAteEmp(XIT.tCheckDataTestAte.tAteEmp ateemp) {
            return base.Channel.ChkUserAteEmp(ateemp);
        }
        
        public string GetErrorCode(string ec) {
            return base.Channel.GetErrorCode(ec);
        }
        
        public string GetErrorCodeXML() {
            return base.Channel.GetErrorCodeXML();
        }
        
        public string SP_PRO_SN_INPUT_MOBILE(string DATA, string MYGROUP, string LINE, string WO, string EMP) {
            return base.Channel.SP_PRO_SN_INPUT_MOBILE(DATA, MYGROUP, LINE, WO, EMP);
        }
        
        public System.Data.DataSet GetWoInfoByWo(string woId) {
            return base.Channel.GetWoInfoByWo(woId);
        }
        
        public string GetWoInfoByWoXml(string woId) {
            return base.Channel.GetWoInfoByWoXml(woId);
        }
        
        public System.Data.DataSet GetProductByPartNumber(string PartNumber) {
            return base.Channel.GetProductByPartNumber(PartNumber);
        }
        
        public string[] GetProductLableNames(string partnumber) {
            return base.Channel.GetProductLableNames(partnumber);
        }
        
        public string[] GetSnMacImeiForAte(string Esn, string sntype, string woId, int snqty) {
            return base.Channel.GetSnMacImeiForAte(Esn, sntype, woId, snqty);
        }
        
        public string[] GetSnMacImeiForAte_2(out string _StrErr, string Esn, string sntype, string woId, int snqty) {
            return base.Channel.GetSnMacImeiForAte_2(out _StrErr, Esn, sntype, woId, snqty);
        }
        
        public string Insert_T_TESTRESULT_INFO(XIT.tCheckDataTestAte.tT_TESTRESULT_INFO tti) {
            return base.Channel.Insert_T_TESTRESULT_INFO(tti);
        }
        
        public string GetWoVersionInfoXML(string woid) {
            return base.Channel.GetWoVersionInfoXML(woid);
        }
        
        public string GetPnMarkBitInfoXML(string pn) {
            return base.Channel.GetPnMarkBitInfoXML(pn);
        }
        
        public System.Data.DataSet GetWoVersionInfoDataSet(string woid) {
            return base.Channel.GetWoVersionInfoDataSet(woid);
        }
        
        public System.Data.DataSet GetPnMarkBitInfoDataSet(string pn) {
            return base.Channel.GetPnMarkBitInfoDataSet(pn);
        }
    }
}
